### PR TITLE
fix(create): Fix resolving path in repos using hoisted node_modules

### LINKED ISSUE #3506: @vendure/create is failing with "Failed to copy email templates"
**Describe the bug**
I am trying to create a new project from scratch and, whether I use manual or quick installation, it fails with the following

```
➜  packages git:(main) ✗ npx @vendure/create my-example
┌  Let's create a Vendure App :sparkles: v3.2.3
│
◇  How should we proceed?
│  Manual Configuration
│
◇  Using port 3000
│
◇  Which database are you using?
│  Postgres
│
◇  What's the database host address?
│  localhost
│
◇  What port is the database listening on?
│  5432
│
◇  What's the name of the database?
│  vendure
│
◇  What's the schema name we should use?
│  public
│
◇  Use SSL to connect to the database? (only enable if your database provider supports SSL)
│  no
│
◇  What's the database user name?
│  postgres
│
◇  What's the database password?
│  postgres
│
◇  What identifier do you want to use for the superadmin user?
│  superadmin
│
◇  What password do you want to use for the superadmin user?
│  superadmin
│
◇  Populate with some sample product data?
│  no
│
◇  Created package.json
│
◇  Successfully installed 6 dependencies
│
◇  Successfully installed 3 dev dependencies
│
◐  Generating app scaffold   Failed to copy email templates.
◇  Generated app scaffold
│
▲  Something went wrong
```

**To Reproduce**
1. Run `npx @verdure/create my-example

**Expected behavior**
A project is initiated

**Environment (please complete the following information):**
 - @vendure/core version: not sure
 - Nodejs version: 23.7.0
 - Database (mysql/postgres etc): postgres

**Additional context**
I am attempting to create the project in a freshly created monorepo

### PR DESCRIPTION
**Pull request by HouseinIsProgramming**
Fixes #3506 

# Description
This PR adds a new helper function that uses `require.resolve()` to find the package directory instead of using `root + /path-to-package`.

This solves the problem where node_modules are hoisted (moved up the directory tree), causing the hardcoded path approach to fail when packages aren't in the expected location.

**Before:** `root + '/node_modules/package-name'`
**After:** `require.resolve('package-name')` to dynamically locate the package

Also adds `process.exit(0)` on errors to prevent "locking the console".

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

## Summary by CodeRabbit

- New Features
  - None

- Bug Fixes
  - Added top-level error handling for the app-creation flow with clearer non-zero exit on failure.
  - Email template copying now reports failures and stops instead of failing silently.

- Refactor
  - Replaced hard-coded module location logic with dynamic package-resolution for improved portability.

- Chores
  - Added a helper to robustly resolve package root directories.

### CODE REVIEW

File: packages/create/src/create-vendure-app.ts [hunk 1]
```diff
@@ -294,13 +298,13 @@ export async function createVendureApp(
 
     // register ts-node so that the config file can be loaded
     // eslint-disable-next-line @typescript-eslint/no-var-requires
-    require(path.join(root, 'node_modules/ts-node')).register();
+    require(path.join(resolveDirName('ts-node'))).register();
```
Comment (michaelbromley) [inline packages/create/src/create-vendure-app.ts]: `path.join` is redundant here

File: packages/create/src/helpers.ts [hunk 2]
```diff
@@ -532,3 +532,30 @@ export function cleanUpDockerResources(name: string) {
         log(pc.yellow(`Could not clean up Docker resources`), { level: 'verbose' });
     }
 }
+
+export function resolveDirName(packageName: string) {
```
Comment (michaelbromley) [inline packages/create/src/helpers.ts]: Can we rename this to `resolvePackageRootDir`? The current name is slightly too generic.
