### PR TITLE
fix(core): Prevent negative order total with fixed discounts

### LINKED ISSUE #1717: Negative order total with fixed amount discount
**Describe the bug**
When a promotion with a fixed discount is greater than the order total, the order total becomes negative.

**To Reproduce**
(this also works on the vendure demo env)
1. Create a promotion that discounts an order by $500
2. Add an item to cart with a price below $500
3. In your cart, or active order, the total price will be -$400

**Expected behavior**
I would expect the order total to be 0 (debatable).

In my case, the Mollie payment fails, because negative. I could fix this in the payment handler, but it might be expected as order total?

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.5
 - Nodejs version 16
 - Database (mysql/postgres etc): MySQL

**Additional context**
image
image

### PR DESCRIPTION
**Pull request by martijnvdbrug**
Prevent negative order total when using fixed discounts. Resolve #1717

### CODE REVIEW

File: packages/dev-server/dev-config.ts [hunk 1]
```diff
@@ -66,8 +66,8 @@ export const devConfig: VendureConfig = {
             assetUploadDir: path.join(__dirname, 'assets'),
         }),
         DefaultSearchPlugin.init({ bufferUpdates: true, indexStockStatus: false }),
-        BullMQJobQueuePlugin.init({}),
-        // DefaultJobQueuePlugin.init(),
```
Comment (martijnvdbrug) [inline packages/dev-server/dev-config.ts:70]: With this line, I am not able to start the dev-server locally without errors. (Docs don't mention anything about a local redis instance)

File: packages/dev-server/dev-config.ts [hunk 2]
```diff
@@ -110,7 +110,7 @@ function getDbConfig(): ConnectionOptions {
         case 'sqlite':
             console.log('Using sqlite connection');
             return {
-                synchronize: false,
```
Comment (martijnvdbrug) [inline packages/dev-server/dev-config.ts:113]: With a clean setup (without local .sql files) the dev-server won't start without synchronize

File: packages/dev-server/dev-config.ts (hunk 1 above)
Comment (michaelbromley) [reply packages/dev-server/dev-config.ts:70]: Yeah that's fine. I just use the BullMQ job queue when I develop because if I ever need to debug DB queries, it is was easier without the polling noise caused by the DefaultJobQueuePlugin.

File: packages/core/src/config/promotion/actions/order-fixed-discount-action.ts [hunk 3]
```diff
@@ -13,7 +13,7 @@ export const orderFixedDiscount = new PromotionOrderAction({
         },
     },
     execute(ctx, order, args) {
-        return -args.discount;
+        return -Math.min(args.discount, order.total);
```
Comment (michaelbromley) [inline packages/core/src/config/promotion/actions/order-fixed-discount-action.ts:16]: ah you use the `order.total` rather than `totalWithTax` because the promotions all operate pre-tax, right? Otherwise we could still end up negative. Is that the case?

Comment (martijnvdbrug) [reply packages/core/src/config/promotion/actions/order-fixed-discount-action.ts:16]: Correct! Also tested with both `channel.pricesIncludeTax=true` and `channel.pricesIncludeTax=false` to be sure

**Comment by martijnvdbrug** [comment]
Windows publishing fails again because of some network error :( @michaelbromley can you rerun failed jobs?

**Comment by michaelbromley** [comment]
Yeah the publish job can be flaky but we can safely ignore it when just a single one fails. Usual networking issues on GH's side.

Just check my second comment and confirm I'm understanding correctly 👍

**Comment by martijnvdbrug** [comment]
@michaelbromley Done! (Thought I already replied, but maybe I had to 'submit review' first)

**Comment by michaelbromley** [comment]
Thanks Martijn!
